let pokemonWebURL = 'https://api.pokemontcg.io/v1/cards?name=';
let bulbapediaURL = 'https://bulbapedia.bulbagarden.net/wiki/';
let bulbapediaEndURL = '_(Pok%C3%A9mon)';
var i = 0;
var jsonObject = {};
var prev_button = document.getElementById("pokemon_prev_nav");
var next_button = document.getElementById("pokemon_next_nav");
var searchError = document.getElementById("ErrorMsgSearch");
var fetchMessage = document.getElementById("FetchingTitle");

prev_button.style.visibility = "hidden";
next_button.style.visibility = "hidden";

function validateInput(){
    /*---deprecated by datalist
    let searchInput = document.getElementById('searchInput2').value;
    ---*/
    let selectInput = document.getElementById('userSearchPokemon').value;
    /*
    if(searchInput == "" && selectInput == "zero"){
        fetchMessage = "Try a different name";
    }
    else if (searchInput != "" && selectInput =="zero"){
        selectMethod(searchInput);
    }
    else if(searchInput != "" && selectInput != "zero"){
        selectMethod(selectInput);
    }
    else if(searchInput == selectInput){
        selectMethod(selectInput);
    }
    */
   selectMethod(selectInput);
}

function selectMethod(inputString){
    try {
        fetchMessage.innerHTML = "Fetching...";
        setTimeout(() => {
            searchPokemonCard(inputString);
            i = 0;
        }, 1000);
    }
    catch (err) {
        console.log(err.message);
    }
}

function searchPokemonCard(searchInput){
    searchError.innerHTML = "";
    fetch(pokemonWebURL + searchInput)
        .then(results => {
            return results.json();
        }).then(results =>{
            if(results.cards.length == 0){
                fetchMessage = "";
                searchError.innerHTML = "Please check the spelling of the name inputted";
            }    
            else {
                inits(results);
                /*jsonObject = results;*/
                console.log(results);
                jsonObject = results;
            }
        })
    /*fetch(bulbapediaURL+searchInput+bulbapediaEndURL)*/
}

function inits(results){
    let type = new Set();
    fetchMessage.innerHTML = "";
    prev_button.style.visibility = "visible";
    next_button.style.visibility = "visible";
    prev_button.disabled = false;
    next_button.disabled = false;
    try{
        let displayCards = document.getElementById("pokemon-display");
        displayCards.src = results.cards[i].imageUrl;
    } 
    catch(err){
        /* deprecated, catch should only contain the error handling
        if(i < 0){
            prev_button.disabled = true;
        }
        else if (i == results.length - 1){
            next_button.disabled = true;
        }
        */
        console.log(i);
        console.log(err.message);
    }
}

function next_nav(){
    if(i < jsonObject.cards.length - 1){
        i += 1;
        inits(jsonObject);
    }
    else{
        i += 0;
        next_button.disabled = true;
    }
    
}

function prev_nav(){
    if(i>0){
        i -= 1;
        inits(jsonObject);
    }
    else{
        i-=0;
        prev_button.disabled=true;
    }

}

/*deprecated*/
function populateSelectFields(){

    var selectPokemon = [
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Nidoran♀",
        "Nidorina",
        "Nidoqueen",
        "Nidoran♂",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetch’d",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "Mr. Mime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew",
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Ledyba",
        "Ledian",
        "Spinarak",
        "Ariados",
        "Crobat",
        "Chinchou",
        "Lanturn",
        "Pichu",
        "Cleffa",
        "Igglybuff",
        "Togepi",
        "Togetic",
        "Natu",
        "Xatu",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Bellossom",
        "Marill",
        "Azumarill",
        "Sudowoodo",
        "Politoed",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Espeon",
        "Umbreon",
        "Murkrow",
        "Slowking",
        "Misdreavus",
        "Unown",
        "Wobbuffet",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Steelix",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Scizor",
        "Shuckle",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Corsola",
        "Remoraid",
        "Octillery",
        "Delibird",
        "Mantine",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Kingdra",
        "Phanpy",
        "Donphan",
        "Porygon2",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Smoochum",
        "Elekid",
        "Magby",
        "Miltank",
        "Blissey",
        "Raikou",
        "Entei",
        "Suicune",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
        "Lugia",
        "Ho-Oh",
        "Celebi",
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Zigzagoon",
        "Linoone",
        "Wurmple",
        "Silcoon",
        "Beautifly",
        "Cascoon",
        "Dustox",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Taillow",
        "Swellow",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Nincada",
        "Ninjask",
        "Shedinja",
        "Whismur",
        "Loudred",
        "Exploud",
        "Makuhita",
        "Hariyama",
        "Azurill",
        "Nosepass",
        "Skitty",
        "Delcatty",
        "Sableye",
        "Mawile",
        "Aron",
        "Lairon",
        "Aggron",
        "Meditite",
        "Medicham",
        "Electrike",
        "Manectric",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Roselia",
        "Gulpin",
        "Swalot",
        "Carvanha",
        "Sharpedo",
        "Wailmer",
        "Wailord",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Spinda",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Lunatone",
        "Solrock",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Baltoy",
        "Claydol",
        "Lileep",
        "Cradily",
        "Anorith",
        "Armaldo",
        "Feebas",
        "Milotic",
        "Castform",
        "Kecleon",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Absol",
        "Wynaut",
        "Snorunt",
        "Glalie",
        "Spheal",
        "Sealeo",
        "Walrein",
        "Clamperl",
        "Huntail",
        "Gorebyss",
        "Relicanth",
        "Luvdisc",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
        "Regirock",
        "Regice",
        "Registeel",
        "Latias",
        "Latios",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys",
        "Turtwig",
        "Grotle",
        "Torterra",
        "Chimchar",
        "Monferno",
        "Infernape",
        "Piplup",
        "Prinplup",
        "Empoleon",
        "Starly",
        "Staravia",
        "Staraptor",
        "Bidoof",
        "Bibarel",
        "Kricketot",
        "Kricketune",
        "Shinx",
        "Luxio",
        "Luxray",
        "Budew",
        "Roserade",
        "Cranidos",
        "Rampardos",
        "Shieldon",
        "Bastiodon",
        "Burmy",
        "Wormadam",
        "Mothim",
        "Combee",
        "Vespiquen",
        "Pachirisu",
        "Buizel",
        "Floatzel",
        "Cherubi",
        "Cherrim",
        "Shellos",
        "Gastrodon",
        "Ambipom",
        "Drifloon",
        "Drifblim",
        "Buneary",
        "Lopunny",
        "Mismagius",
        "Honchkrow",
        "Glameow",
        "Purugly",
        "Chingling",
        "Stunky",
        "Skuntank",
        "Bronzor",
        "Bronzong",
        "Bonsly",
        "Mime Jr.",
        "Happiny",
        "Chatot",
        "Spiritomb",
        "Gible",
        "Gabite",
        "Garchomp",
        "Munchlax",
        "Riolu",
        "Lucario",
        "Hippopotas",
        "Hippowdon",
        "Skorupi",
        "Drapion",
        "Croagunk",
        "Toxicroak",
        "Carnivine",
        "Finneon",
        "Lumineon",
        "Mantyke",
        "Snover",
        "Abomasnow",
        "Weavile",
        "Magnezone",
        "Lickilicky",
        "Rhyperior",
        "Tangrowth",
        "Electivire",
        "Magmortar",
        "Togekiss",
        "Yanmega",
        "Leafeon",
        "Glaceon",
        "Gliscor",
        "Mamoswine",
        "Porygon-Z",
        "Gallade",
        "Probopass",
        "Dusknoir",
        "Froslass",
        "Rotom",
        "Uxie",
        "Mesprit",
        "Azelf",
        "Dialga",
        "Palkia",
        "Heatran",
        "Regigigas",
        "Giratina",
        "Cresselia",
        "Phione",
        "Manaphy",
        "Darkrai",
        "Shaymin",
        "Arceus",
        "Victini",
        "Snivy",
        "Servine",
        "Serperior",
        "Tepig",
        "Pignite",
        "Emboar",
        "Oshawott",
        "Dewott",
        "Samurott",
        "Patrat",
        "Watchog",
        "Lillipup",
        "Herdier",
        "Stoutland",
        "Purrloin",
        "Liepard",
        "Pansage",
        "Simisage",
        "Pansear",
        "Simisear",
        "Panpour",
        "Simipour",
        "Munna",
        "Musharna",
        "Pidove",
        "Tranquill",
        "Unfezant",
        "Blitzle",
        "Zebstrika",
        "Roggenrola",
        "Boldore",
        "Gigalith",
        "Woobat",
        "Swoobat",
        "Drilbur",
        "Excadrill",
        "Audino",
        "Timburr",
        "Gurdurr",
        "Conkeldurr",
        "Tympole",
        "Palpitoad",
        "Seismitoad",
        "Throh",
        "Sawk",
        "Sewaddle",
        "Swadloon",
        "Leavanny",
        "Venipede",
        "Whirlipede",
        "Scolipede",
        "Cottonee",
        "Whimsicott",
        "Petilil",
        "Lilligant",
        "Basculin",
        "Sandile",
        "Krokorok",
        "Krookodile",
        "Darumaka",
        "Darmanitan",
        "Maractus",
        "Dwebble",
        "Crustle",
        "Scraggy",
        "Scrafty",
        "Sigilyph",
        "Yamask",
        "Cofagrigus",
        "Tirtouga",
        "Carracosta",
        "Archen",
        "Archeops",
        "Trubbish",
        "Garbodor",
        "Zorua",
        "Zoroark",
        "Minccino",
        "Cinccino",
        "Gothita",
        "Gothorita",
        "Gothitelle",
        "Solosis",
        "Duosion",
        "Reuniclus",
        "Ducklett",
        "Swanna",
        "Vanillite",
        "Vanillish",
        "Vanilluxe",
        "Deerling",
        "Sawsbuck",
        "Emolga",
        "Karrablast",
        "Escavalier",
        "Foongus",
        "Amoonguss",
        "Frillish",
        "Jellicent",
        "Alomomola",
        "Joltik",
        "Galvantula",
        "Ferroseed",
        "Ferrothorn",
        "Klink",
        "Klang",
        "Klinklang",
        "Tynamo",
        "Eelektrik",
        "Eelektross",
        "Elgyem",
        "Beheeyem",
        "Litwick",
        "Lampent",
        "Chandelure",
        "Axew",
        "Fraxure",
        "Haxorus",
        "Cubchoo",
        "Beartic",
        "Cryogonal",
        "Shelmet",
        "Accelgor",
        "Stunfisk",
        "Mienfoo",
        "Mienshao",
        "Druddigon",
        "Golett",
        "Golurk",
        "Pawniard",
        "Bisharp",
        "Bouffalant",
        "Rufflet",
        "Braviary",
        "Vullaby",
        "Mandibuzz",
        "Heatmor",
        "Durant",
        "Deino",
        "Zweilous",
        "Hydreigon",
        "Larvesta",
        "Volcarona",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Reshiram",
        "Zekrom",
        "Landorus",
        "Kyurem",
        "Keldeo",
        "Meloetta",
        "Genesect",
        "Chespin",
        "Quilladin",
        "Chesnaught",
        "Fennekin",
        "Braixen",
        "Delphox",
        "Froakie",
        "Frogadier",
        "Greninja",
        "Bunnelby",
        "Diggersby",
        "Fletchling",
        "Fletchinder",
        "Talonflame",
        "Scatterbug",
        "Spewpa",
        "Vivillon",
        "Litleo",
        "Pyroar",
        "Flabebe",
        "Floette",
        "Florges",
        "Skiddo",
        "Gogoat",
        "Pancham",
        "Pangoro",
        "Furfrou",
        "Espurr",
        "Meowstic",
        "Honedge",
        "Doublade",
        "Aegislash",
        "Spritzee",
        "Aromatisse",
        "Swirlix",
        "Slurpuff",
        "Inkay",
        "Malamar",
        "Binacle",
        "Barbaracle",
        "Skrelp",
        "Dragalge",
        "Clauncher",
        "Clawitzer",
        "Helioptile",
        "Heliolisk",
        "Tyrunt",
        "Tyrantrum",
        "Amaura",
        "Aurorus",
        "Sylveon",
        "Hawlucha",
        "Dedenne",
        "Carbink",
        "Goomy",
        "Sliggoo",
        "Goodra",
        "Klefki",
        "Phantump",
        "Trevenant",
        "Pumpkaboo",
        "Gourgeist",
        "Bergmite",
        "Avalugg",
        "Noibat",
        "Noivern",
        "Xerneas",
        "Yveltal",
        "Zygarde",
        "Diancie",
        "Hoopa",
        "Volcanion",
        "Rowlet",
        "Dartrix",
        "Decidueye",
        "Litten",
        "Torracat",
        "Incineroar",
        "Popplio",
        "Brionne",
        "Primarina",
        "Pikipek",
        "Trumbeak",
        "Toucannon",
        "Yungoos",
        "Gumshoos",
        "Grubbin",
        "Charjabug",
        "Vikavolt",
        "Crabrawler",
        "Crabominable",
        "Oricorio",
        "Cutiefly",
        "Ribombee",
        "Rockruff",
        "Lycanroc",
        "Wishiwashi",
        "Mareanie",
        "Toxapex",
        "Mudbray",
        "Mudsdale",
        "Dewpider",
        "Araquanid",
        "Fomantis",
        "Lurantis",
        "Morelull",
        "Shiinotic",
        "Salandit",
        "Salazzle",
        "Stufful",
        "Bewear",
        "Bounsweet",
        "Steenee",
        "Tsareena",
        "Comfey",
        "Oranguru",
        "Passimian",
        "Wimpod",
        "Golisopod",
        "Sandygast",
        "Palossand",
        "Pyukumuku",
        "Type: Null",
        "Silvally",
        "Minior",
        "Komala",
        "Turtonator",
        "Togedemaru",
        "Mimikyu",
        "Bruxish",
        "Drampa",
        "Dhelmise",
        "Jangmo-o",
        "Hakamo-o",
        "Kommo-o",
        "Tapu Koko",
        "Tapu Lele",
        "Tapu Bulu",
        "Tapu Fini",
        "Cosmog",
        "Cosmoem",
        "Solgaleo",
        "Lunala",
        "Nihilego",
        "Buzzwole",
        "Pheromosa",
        "Xurkitree",
        "Celesteela",
        "Kartana",
        "Guzzlord",
        "Necrozma",
        "Magearna",
        "Marshadow",
        "Poipole",
        "Naganadel",
        "Stakataka",
        "Blacephalon",
        "Zeraora",
        "Meltan",
        "Melmetal"
    ];

    var selectPokemon2 = [{ "id": 810, "name": "Grookey", "types": ["grass"] }, { "id": 811, "name": "Thwackey", "types": ["grass"] }, { "id": 812, "name": "Rillaboom", "types": ["grass"] }, { "id": 813, "name": "Scorbunny", "types": ["fire"] }, { "id": 814, "name": "Raboot", "types": ["fire"] }, { "id": 815, "name": "Cinderace", "types": ["fire"] }, { "id": 816, "name": "Sobble", "types": ["water"] }, { "id": 817, "name": "Drizzile", "types": ["water"] }, { "id": 818, "name": "Inteleon", "types": ["water"] }, { "id": 819, "name": "Skwovet", "types": ["normal"] }, { "id": 820, "name": "Greedent", "types": ["normal"] }, { "id": 821, "name": "Rookidee", "types": ["flying"] }, { "id": 822, "name": "Corvisquire", "types": ["flying"] }, { "id": 823, "name": "Corviknight", "types": ["flying", "steel"] }, { "id": 824, "name": "Blipbug", "types": ["bug"] }, { "id": 825, "name": "Dottler", "types": ["bug", "psychic"] }, { "id": 826, "name": "Orbeetle", "types": ["bug", "psychic"] }, { "id": 827, "name": "Nickit", "types": ["dark"] }, { "id": 828, "name": "Thievul", "types": ["dark"] }, { "id": 829, "name": "Gossifleur", "types": ["grass"] }, { "id": 830, "name": "Eldegoss", "types": ["grass"] }, { "id": 831, "name": "Wooloo", "types": ["normal"] }, { "id": 832, "name": "Dubwool", "types": ["normal"] }, { "id": 833, "name": "Chewtle", "types": ["water"] }, { "id": 834, "name": "Drednaw", "types": ["water", "rock"] }, { "id": 835, "name": "Yamper", "types": ["electric"] }, { "id": 836, "name": "Boltund", "types": ["electric"] }, { "id": 837, "name": "Rolycoly", "types": ["rock"] }, { "id": 838, "name": "Carkol", "types": ["rock", "fire"] }, { "id": 839, "name": "Coalossal", "types": ["rock", "fire"] }, { "id": 840, "name": "Applin", "types": ["grass", "dragon"] }, { "id": 841, "name": "Flapple", "types": ["grass", "dragon"] }, { "id": 842, "name": "Appletun", "types": ["grass", "dragon"] }, { "id": 843, "name": "Silicobra", "types": ["ground"] }, { "id": 844, "name": "Sandaconda", "types": ["ground"] }, { "id": 845, "name": "Cramorant", "types": ["flying", "water"] }, { "id": 846, "name": "Arrokuda", "types": ["water"] }, { "id": 847, "name": "Barraskewda", "types": ["water"] }, { "id": 848, "name": "Toxel", "types": ["electric", "poison"] }, { "id": 849, "name": "Toxtricity", "types": ["electric", "poison"] }, { "id": 850, "name": "Sizzlipede", "types": ["fire", "bug"] }, { "id": 851, "name": "Centiskorch", "types": ["fire", "bug"] }, { "id": 852, "name": "Clobbopus", "types": ["fighting"] }, { "id": 853, "name": "Grapploct", "types": ["fighting"] }, { "id": 854, "name": "Sinistea", "types": ["ghost"] }, { "id": 855, "name": "Polteageist", "types": ["ghost"] }, { "id": 856, "name": "Hatenna", "types": ["psychic"] }, { "id": 857, "name": "Hattrem", "types": ["psychic"] }, { "id": 858, "name": "Hatterene", "types": ["psychic", "fairy"] }, { "id": 859, "name": "Impidimp", "types": ["dark", "fairy"] }, { "id": 860, "name": "Morgrem", "types": ["dark", "fairy"] }, { "id": 861, "name": "Grimmsnarl", "types": ["dark", "fairy"] }, { "id": 862, "name": "Obstagoon", "types": ["dark", "normal"] }, { "id": 863, "name": "Perrserker", "types": ["steel"] }, { "id": 864, "name": "Cursola", "types": ["ghost"] }, { "id": 865, "name": "Sirfetch'd", "types": ["fighting"] }, { "id": 866, "name": "Mr. Rime", "types": ["ice", "psychic"] }, { "id": 867, "name": "Runerigus", "types": ["ground", "ghost"] }, { "id": 868, "name": "Milcery", "types": ["fairy"] }, { "id": 869, "name": "Alcremie", "types": ["fairy"] }, { "id": 870, "name": "Falinks", "types": ["fighting"] }, { "id": 871, "name": "Pincurchin", "types": ["electric"] }, { "id": 872, "name": "Snom", "types": ["ice", "bug"] }, { "id": 873, "name": "Frosmoth", "types": ["ice", "bug"] }, { "id": 874, "name": "Stonjourner", "types": ["rock"] }, { "id": 875, "name": "Eiscue", "types": ["ice"] }, { "id": 876, "name": "Indeedee", "types": ["psychic", "normal"] }, { "id": 877, "name": "Morpeko", "types": ["electric", "dark"] }, { "id": 878, "name": "Cufant", "types": ["steel"] }, { "id": 879, "name": "Copperajah", "types": ["steel"] }, { "id": 880, "name": "Dracozolt", "types": ["electric", "dragon"] }, { "id": 881, "name": "Arctozolt", "types": ["electric", "ice"] }, { "id": 882, "name": "Dracovish", "types": ["water", "dragon"] }, { "id": 883, "name": "Arctovish", "types": ["water", "ice"] }, { "id": 884, "name": "Duraludon", "types": ["steel", "dragon"] }, { "id": 885, "name": "Dreepy", "types": ["dragon", "ghost"] }, { "id": 886, "name": "Drakloak", "types": ["dragon", "ghost"] }, { "id": 887, "name": "Dragapult", "types": ["dragon", "ghost"] }, { "id": 888, "name": "Zacian", "types": ["fairy"] }, { "id": 889, "name": "Zamazenta", "types": ["fighting"] }, { "id": 890, "name": "Eternatus", "types": ["poison", "dragon"]}];

    let pokemonDropdown = document.getElementById("pokemon-dropdown");
    pokemonDropdown.length= 0;

    let defaultPokemonOption = document.createElement("option");
    defaultPokemonOption.text = 'Choose your Pokemon';
    let pokemonOption = document.createElement("option");

    pokemonDropdown.add(defaultPokemonOption);
    pokemonDropdown.selectedIndex = 0;

    for(let i = 0; i < selectPokemon.length; i++){
        option = document.createElement("option");
        option.text = selectPokemon[i];
        option.value = selectPokemon[i];
        pokemonDropdown.add(option);
    }
    for(let k=0; k < selectPokemon2.length; k++){
        console.log(selectPokemon2[k].name);
        option = document.createElement("option");
        option.text = selectPokemon2[k].name;
        option.value = selectPokemon2[k].name;
        pokemonDropdown.add(option);
    }
}


/*window.onload = populateSelectFields();*/

